### ISSUE TITLE
这个插件是否支持在vscode这边进行小程序云函数的添加、上传、更新等操作？

### ISSUE THREAD

**Issue by Chorer** [TencentCloudBase/cloudbase-toolkit#1]

**Comment by chhpt** [comment]
@Chorer 是支持的

**Comment by Chorer** [comment]
@chhpt  我按照原先通过开发者工具部署的云环境，在vscode这边进行相关配置，但是无法读取这个环境，不知道是不是哪里配置错误。尝试阅读文档，但是没找到相关的说明

![](https://i.loli.net/2020/07/08/USGMYoQwcn8Oa4j.png)

**Comment by chhpt** [comment]
@Chorer 你登录的账号可能是错的，报错信息是环境不存在。

**Comment by Chorer** [comment]
感谢，问题已解决，确实是登录的问题。还有就是自动生成的cloudbaserc,json文件需要手动修改functionRoot的路径为自己云函数的文件夹名字，这样就不会报错了
