### ISSUE TITLE
上传到静态网站功能问题

### ISSUE THREAD

**Issue by wenkm** [TencentCloudBase/cloudbase-toolkit#3]
当文件夹下还有文件夹的时候，里面的文件不能按照路径正确上传。
比如：
/dist/js/app.js 上传后变成了 app.js，目录结构没有得到保留。
使用tcb命令不存在这个问题。

**Comment by chhpt** [comment]
上传文件时，要手动输入路径，否则会直接上传到根目录

**Comment by wenkm** [comment]
是设置了路径的，比如设置的/abc，所有文件都放到/abc下面了，/dist/js/app.js按理说路径应该是/abc/js/app.js，而实际却是/abc/app.js
![image](https://user-images.githubusercontent.com/3335540/103278859-726e7480-4a07-11eb-95c0-29451d80c308.png)

**Comment by chhpt** [comment]
上传的路径是你输入的路径 + 文件名，如果要上传到 /dist/js/app.js，请输入 /dist/js 路径
